## YAML Template.
signals: 
    /odom:
        samples: 2
        window_size: 5
        max_delay: 0.05
        max_diff: 0.1
        min_diff: 0.025
    /cmd_vel:
        samples: 2
        window_size: 10
        max_delay: 0.1
        max_diff: 0.3
        min_diff: -0.1
    /phone1/android/imu:
        samples: 2
        window_size: 10
        max_delay: 0.2
        max_diff: 3.0
        min_diff: 0.0
    /phone1/android/fix:
        samples: 3
        window_size: 2
        max_delay: 1.0
        max_diff: 1450.0
        min_diff: 0.0

    /wheel_angles:
        samples: 2
        window_size: 5
        max_delay: 0.1
        max_diff: 0.05
        min_diff: 0.01
    /left_speed:
        samples: 2
        window_size: 5
        max_delay: 0.05
        max_diff: 0.05
        min_diff: 0.01
    /right_speed:
        samples: 2
        window_size: 5
        max_delay: 0.1
        max_diff: 0.05
        min_diff: 0.01
faults:
    # stopped_robot:
    #    - /cmd_vel
    odom_publisher_fault:
        - /odom
    stuck_left_wheel:
        - /left_speed
    stuck_right_wheel:
        - /right_speed
    imu_manager_is_dead:
        - /imu/data_raw
        - /imu/data_raw_transformed
    collision:
        - /phone1/android/imu
    robot_lost:
        - /phone1/android/fix
    android_unplugged:
        - /phone1/android/imu
        - /phone1/android/fix
    wheels:
        - /wheel_angles
    navigation_map_server:
        - /navigation/map
        
recovery:
    imu_manager_is_dead: 
        strategy: stop_action
        args: imu_manager
    collision: 
        strategy: stop_action
        args: imu_manager