CUT:
  planner: inside_planner
  controller: diff
  tool_info:
    topic: "/tool_cut"
    type_str: int
    high_value: 120
    low_value: 0
COLLECT:
  planner: inside_planner
  controller: diff
  tool_info:
    topic: "/Pickup"
    type_str: int
    high_value: 120
    low_value: 0
FREE_MOTION:
  planner: inside_planner
  controller: diff
CONTAINER:
  x: 0 #-16
  y: 0 #-25
  yaw: 1.571
  planner: carrot
  controller: diff
