CUT:
  planner: default
  controller: car
COLLECT:
  planner: default
  controller: car
FREE_MOTION:
  planner: default
  controller: diff
CONTAINER:
  x: 0
  #-16
  y: 0
  #-25
  yaw: 1.571
  planner: navfn
  controller: diff
