CUT:
  planner: carrot
  controller: car
COLLECT:
  planner: carrot
  controller: car
FREE_MOTION:
  planner: inside_planner
  controller: diff
CONTAINER:
  x: 0 #-16
  y: 0 #-25
  yaw: 1.571
  planner: outside_planner
  controller: diff
